package main

import (
	"fmt"
	"time"

	"github.com/go-zoox/fetch"
)

type AutoGenerated struct {
	Runs []struct {
		Summary struct {
			Season  string `json:"season"`
			Status  string `json:"status"`
			Dungeon struct {
				Type                   string `json:"type"`
				ID                     int    `json:"id"`
				Name                   string `json:"name"`
				ShortName              string `json:"short_name"`
				Slug                   string `json:"slug"`
				ExpansionID            int    `json:"expansion_id"`
				IconURL                string `json:"icon_url"`
				Patch                  string `json:"patch"`
				WowInstanceID          int    `json:"wowInstanceId"`
				MapChallengeModeID     int    `json:"map_challenge_mode_id"`
				KeystoneTimerMs        int    `json:"keystone_timer_ms"`
				NumBosses              int    `json:"num_bosses"`
				GroupFinderActivityIds []int  `json:"group_finder_activity_ids"`
			} `json:"dungeon"`
			KeystoneRunID   int           `json:"keystone_run_id"`
			MythicLevel     int           `json:"mythic_level"`
			ClearTimeMs     int           `json:"clear_time_ms"`
			KeystoneTimeMs  int           `json:"keystone_time_ms"`
			CompletedAt     time.Time     `json:"completed_at"`
			NumChests       int           `json:"num_chests"`
			TimeRemainingMs int           `json:"time_remaining_ms"`
			LoggedRunID     int           `json:"logged_run_id"`
			Videos          []interface{} `json:"videos"`
			WeeklyModifiers []struct {
				ID          int    `json:"id"`
				Icon        string `json:"icon"`
				Name        string `json:"name"`
				Slug        string `json:"slug"`
				Description string `json:"description"`
			} `json:"weekly_modifiers"`
			NumModifiersActive int         `json:"num_modifiers_active"`
			Faction            string      `json:"faction"`
			DeletedAt          interface{} `json:"deleted_at"`
			Role               string      `json:"role"`
			DoesVideoExist     bool        `json:"doesVideoExist"`
		} `json:"summary"`
		Score int `json:"score"`
	} `json:"runs"`
	UI struct {
		Season      string `json:"season"`
		CharacterID int    `json:"characterId"`
		DungeonID   int    `json:"dungeonId"`
		Role        string `json:"role"`
		SpecID      int    `json:"specId"`
		Mode        string `json:"mode"`
		Affixes     string `json:"affixes"`
		Date        string `json:"date"`
	} `json:"ui"`
}

func main() {

	var dungeonIds []map[string]string = []map[string]string{}
	dungeonIds = append(dungeonIds, map[string]string{"1000001": "Tazavesh: So'leah's Gambit"})
	dungeonIds = append(dungeonIds, map[string]string{"1000000": "Tazavesh: Streets of Wonder"})
	dungeonIds = append(dungeonIds, map[string]string{"12831": "Halls of Atonement"})
	dungeonIds = append(dungeonIds, map[string]string{"1281509331": "Ara-Kara, City of Echoes"})
	dungeonIds = append(dungeonIds, map[string]string{"15452": "Operation: Floodgate"})
	dungeonIds = append(dungeonIds, map[string]string{"14971": "The Dawnbreaker"})
	dungeonIds = append(dungeonIds, map[string]string{"16104": "Eco-Dome Al'dani"})
	dungeonIds = append(dungeonIds, map[string]string{"14954": "Priory of the Sacred Flame"})

	blubb := []string{
		"1000001", "1000000", "12831", "1281509331", "15452", "14971", "16104", "14954",
	}

	var baseURL = "https://raider.io/api/characters/mythic-plus-runs?season=season-tww-3"

	for _, dungeonId := range blubb {
		url := baseURL + "&236673948&dungeonId=" + dungeonId
		fmt.Println(url)
		response, err := fetch.Get(url)
		if err != nil {
			panic(err)
		}
		fmt.Println(response.JSON())
	}

}
